spring:
  datasource:
    password: luciano
    username: root
    url: 'jdbc:mysql://localhost:3307/fornecedor?useTimezone=true&“amp”;serverTimezone=UTC'
  jpa:
    hibernate:
      ddl-auto: update
